services:
  lb:
    build: ./round-robin
    depends_on:
      - node1
      - node2
    ports:
      - "8080:8080"
    environment:
       - nodes=node1:8081,node2:8081
    links:
      - node1:node1
      - node2:node2
    networks:
      - gateway

  node1:
     container_name: node1
     build: /node
     environment:
       - name="Node1"
     ports:
       - "8081:8081"
     networks:
       - gateway
  node2:
     container_name: node2
     build: /node
     environment:
       - name="Node2"
     ports:
       - "8082:8081"
     networks:
       - gateway
networks:
  gateway: {}
